
// 1 //
let int = prompt('любще число')
if(int % 2 === 1 ){
    console.log("not even ")
} else( 
    console.log("even")
)
//  2 //

let name = prompt("как тебя зовут")
if( name >= "A || a" + "lex"){
    console.log("you can go through")
} else(
    console.log("go home ")
) 

// 3 //
let age = prompt("сколько тебе лет ")
if(age >= '18'){
    console.log("you can go through")
} else(
    console.log("go home ")
)